"""make_buy_tx_id_nullable

Revision ID: 2e035bcf04a3
Revises: ca296d222b87
Create Date: 2026-03-14 03:52:25.791298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e035bcf04a3'
down_revision: Union[str, Sequence[str], None] = 'ca296d222b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_lot_consumptions', schema=None) as batch_op:
        batch_op.alter_column('buy_tx_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_lot_consumptions', schema=None) as batch_op:
        batch_op.alter_column('buy_tx_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
