"""add tax lot consumption and update transactions

Revision ID: 424384f7cb0a
Revises: ae5f941ae279
Create Date: 2026-03-13 16:45:47.598381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424384f7cb0a'
down_revision: Union[str, Sequence[str], None] = 'ae5f941ae279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('tax_lot_consumptions', ... ) - already dropped and will recreate
    op.create_table('tax_lot_consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sell_tx_id', sa.Integer(), nullable=False),
    sa.Column('buy_tx_id', sa.Integer(), nullable=False),
    sa.Column('amount_consumed', sa.Float(), nullable=False),
    sa.Column('ils_value_consumed', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['buy_tx_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['sell_tx_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_lot_consumptions_id'), 'tax_lot_consumptions', ['id'], unique=False)
    # with op.batch_alter_table('transactions') as batch_op:
    #     batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
    #     batch_op.add_column(sa.Column('parent_tx_id', sa.Integer(), nullable=True))
    
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.create_foreign_key('fk_transactions_parent_tx_id', 'transactions', ['parent_tx_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.drop_constraint('fk_transactions_parent_tx_id', type_='foreignkey')
        batch_op.drop_column('parent_tx_id')
        batch_op.drop_column('is_active')
    op.drop_index(op.f('ix_tax_lot_consumptions_id'), table_name='tax_lot_consumptions')
    op.drop_table('tax_lot_consumptions')
    # ### end Alembic commands ###
