"""add historical_price table

Revision ID: 6375fac279c9
Revises: 8ad4db30a49d
Create Date: 2026-03-14 21:00:34.566411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6375fac279c9'
down_revision: Union[str, Sequence[str], None] = '8ad4db30a49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_prices',
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('asset', 'date')
    )
    with op.batch_alter_table('historical_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_prices_asset'), ['asset'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_prices_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_prices_date'))
        batch_op.drop_index(batch_op.f('ix_historical_prices_asset'))

    op.drop_table('historical_prices')
    # ### end Alembic commands ###
