"""add_app_setting_table

Revision ID: 8ad4db30a49d
Revises: 2e035bcf04a3
Create Date: 2026-03-14 07:15:57.681199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad4db30a49d'
down_revision: Union[str, Sequence[str], None] = '2e035bcf04a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))
        batch_op.drop_index(batch_op.f('ix_app_settings_id'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
