"""Add coinly parity fields

Revision ID: ae5f941ae279
Revises: 
Create Date: 2026-03-13 15:24:16.330797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5f941ae279'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('ghost') - Safety check if exists
    op.add_column('transactions', sa.Column('is_issue', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('issue_notes', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('category', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('linked_transaction_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'linked_transaction_id')
    op.drop_column('transactions', 'category')
    op.drop_column('transactions', 'issue_notes')
    op.drop_column('transactions', 'is_issue')
    # ### end Alembic commands ###
