"""add_manual_cost_basis_fields

Revision ID: ca296d222b87
Revises: b3d55099a52c
Create Date: 2026-03-14 03:51:52.286650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca296d222b87'
down_revision: Union[str, Sequence[str], None] = 'b3d55099a52c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('manual_cost_basis_ils', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('manual_purchase_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'manual_purchase_date')
    op.drop_column('transactions', 'manual_cost_basis_ils')
    # ### end Alembic commands ###
